### ISSUE TITLE
WebApp crashes RedMatic - TypeError: Cannot read property 'TYPE' of undefined

### ISSUE THREAD

**Issue by stan23** [rdmtc/RedMatic-WebApp#24]
Ich habe WebApp zu einer frischen RedMatic Installation hinzugefügt und (soweit ich mich erinnere) zur Standartkonfiguration nur Systemvariablen (?) mit ausgewählt.

Nun crasht RedMatic:
```

Oct  8 08:29:58 homematic-raspi user.info redmatic: RedMatic v1.6.0 (c) Sebastian Raff https://github.com/hobbyquaker/RedMatic
Oct  8 08:29:58 homematic-raspi user.info redmatic: Started Node-RED
Oct  8 08:30:03 homematic-raspi daemon.info node-red[6415]: Welcome to Node-RED
Oct  8 08:30:03 homematic-raspi daemon.info node-red[6415]: ===================
Oct  8 08:30:03 homematic-raspi daemon.info node-red[6415]: Node-RED version: v0.19.4
Oct  8 08:30:03 homematic-raspi daemon.info node-red[6415]: Node.js  version: v8.12.0
Oct  8 08:30:03 homematic-raspi daemon.info node-red[6415]: Linux 4.14.70 arm LE
Oct  8 08:30:04 homematic-raspi daemon.info node-red[6415]: Loading palette nodes
Oct  8 08:30:10 homematic-raspi daemon.info node-red[6415]: node-red-contrib-ccu version: 1.6.12
Oct  8 08:30:11 homematic-raspi daemon.info node-red[6415]: Dashboard version 2.9.8 started at /addons/red/ui
Oct  8 08:30:12 homematic-raspi daemon.info node-red[6415]: Settings file  : /usr/local/addons/redmatic/lib/settings.js
Oct  8 08:30:12 homematic-raspi daemon.info node-red[6415]: Context store  : 'default' [module=localfilesystem]
Oct  8 08:30:12 homematic-raspi daemon.info node-red[6415]: User directory : /usr/local/addons/redmatic/var
Oct  8 08:30:12 homematic-raspi daemon.warn node-red[6415]: Projects disabled : editorTheme.projects.enabled=false
Oct  8 08:30:12 homematic-raspi daemon.info node-red[6415]: Flows file     : /usr/local/addons/redmatic/var/flows.json
Oct  8 08:30:12 homematic-raspi daemon.info node-red[6415]: Starting flows
Oct  8 08:30:13 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] paramsets loaded from /usr/local/addons/redmatic/var/ccu_paramsets_v2.json
Oct  8 08:30:13 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] metadata loaded from /usr/local/addons/redmatic/var/ccu_localhost.json
Oct  8 08:30:14 homematic-raspi daemon.info node-red[6415]: RedMatic-WebApp started at /addons/red/app
Oct  8 08:30:14 homematic-raspi daemon.info node-red[6415]: Started flows
Oct  8 08:30:14 homematic-raspi daemon.info node-red[6415]: Server now running at http://127.0.0.1:1880/addons/red/
Oct  8 08:30:15 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
Oct  8 08:30:15 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] binrpc server listening on binrpc://127.0.0.1:2047
Oct  8 08:30:15 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] xmlrpc server listening on http://127.0.0.1:2048
Oct  8 08:30:15 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] HmIP-RF connected
Oct  8 08:30:15 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] ReGaHSS connected
Oct  8 08:30:15 homematic-raspi daemon.info node-red[6415]: [ccu-connection:localhost] BidCos-RF connected
Oct  8 08:30:19 homematic-raspi daemon.info node-red[6415]: RedMatic-WebApp getConfig "app" from 127.0.0.1
Oct  8 08:30:19 homematic-raspi daemon.err node-red: 8 Oct 08:30:19 - [red] Uncaught Exception:
Oct  8 08:30:19 homematic-raspi daemon.err node-red: 8 Oct 08:30:19 - TypeError: Cannot read property 'TYPE' of undefined
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at ccu.channelRooms.(anonymous function).forEach.room (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/nodes/redmatic-webapp.js:85:70)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at Array.forEach (<anonymous>)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at Object.keys.forEach.channel (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/nodes/redmatic-webapp.js:78:56)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at Array.forEach (<anonymous>)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at Conn.RedMaticWebApp.conn.getData (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/nodes/redmatic-webapp.js:76:52)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at Socket.socket.on (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/backend.js:75:44)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at emitTwo (events.js:126:13)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at Socket.emit (events.js:214:7)
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/redmatic-webapp/node_modules/socket.io/lib/socket.js:528:12
Oct  8 08:30:19 homematic-raspi daemon.err node-red:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
```

Kann man die Konfiguration löschen selbst wenn RedMatic nicht startet?

**Comment by stan23** [comment]
Nach ein paar weiteren Versuchen crasht RedMatic offenbar nicht direkt nach dem Starten, sondern wenn man WebApp öffnet oder noch im Browser offen hat.

Auch wenn ich alle Räume in der Konfiguration der WebApp explizit abwähle, gibt es den gleichen Crash - hier mit Loglevel _Trace_:
```
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] updateRegaVariable {"id":19465,"name":"Wired-Status","info":"Wired-Status","val":true,"ts":1538981640000,"min":null,"max":null,"unit":"","type":"boolean","enum":["offline","online"],"channel":"65535"}
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] match false {"name":"Anwesenheit","cache":true,"change":true} name:Wired-Status cache:true change:false
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] match false {"name":"Alarmzone 1","cache":true,"change":true} name:Wired-Status cache:true change:false
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] match false {} name:Wired-Status cache:true change:false
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] {"id":9481,"name":"WT SV Durchschnittstemperatur","info":"","val":21.55,"ts":"2018-10-08 08:52:32","min":0,"max":100,"unit":"°C","type":"number","enum":[],"channel":"65535"}
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] updateRegaVariable {"id":9481,"name":"WT SV Durchschnittstemperatur","info":"","val":21.55,"ts":1538981552000,"min":0,"max":100,"unit":"°C","type":"number","enum":[],"channel":"65535"}
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] match false {"name":"Anwesenheit","cache":true,"change":true} name:WT SV Durchschnittstemperatur cache:true change:false
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] match false {"name":"Alarmzone 1","cache":true,"change":true} name:WT SV Durchschnittstemperatur cache:true change:false
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] match false {} name:WT SV Durchschnittstemperatur cache:true change:false
Oct  8 08:54:21 homematic-raspi daemon.info node-red[2323]: [ccu-connection:localhost] ReGaHSS connected
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] getRegaPrograms
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost]     < BidCos-RF init ""
Oct  8 08:54:21 homematic-raspi daemon.info node-red[2323]: [ccu-connection:localhost] BidCos-RF connected
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] rpcCheckInit BidCos-RF 0 60
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] rega next poll in 30 seconds
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost] rpc > BidCos-RF listBidcosInterfaces []
Oct  8 08:54:21 homematic-raspi daemon.debug node-red[2323]: [ccu-connection:localhost]     < BidCos-RF listBidcosInterfaces [{"ADDRESS":"OEQ0307015","CONNECTED":true,"DEFAULT":true,"DESCRIPTION":"CCU2-Coprocessor","DUTY_CYCLE":9,"FIRMWARE_VERSION":"2.8.6","TYPE":"CCU2"}]
Oct  8 08:54:22 homematic-raspi daemon.debug node-red[2323]: RedMatic-WebApp connect from 127.0.0.1
Oct  8 08:54:22 homematic-raspi daemon.info node-red[2323]: RedMatic-WebApp getConfig "app" from 127.0.0.1
Oct  8 08:54:22 homematic-raspi daemon.err node-red: 8 Oct 08:54:22 - [red] Uncaught Exception:
Oct  8 08:54:22 homematic-raspi daemon.err node-red: 8 Oct 08:54:22 - TypeError: Cannot read property 'TYPE' of undefined
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at ccu.channelRooms.(anonymous function).forEach.room (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/nodes/redmatic-webapp.js:85:70)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at Array.forEach (<anonymous>)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at Object.keys.forEach.channel (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/nodes/redmatic-webapp.js:78:56)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at Array.forEach (<anonymous>)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at Conn.RedMaticWebApp.conn.getData (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/nodes/redmatic-webapp.js:76:52)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at Socket.socket.on (/usr/local/addons/redmatic/var/node_modules/redmatic-webapp/backend.js:75:44)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at emitTwo (events.js:126:13)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at Socket.emit (events.js:214:7)
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at /usr/local/addons/redmatic/var/node_modules/redmatic-webapp/node_modules/socket.io/lib/socket.js:528:12
Oct  8 08:54:22 homematic-raspi daemon.err node-red:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
```

**Comment by hobbyquaker** [comment]
Sollte in RedMatic-WebApp 0.2.1 behoben sein. Wenn Du das Update machen möchtest bevor ein neues RedMatic Release zur Verfügung steht geht das manuell wie folgt:

```
export PATH=/usr/local/addons/redmatic/bin:$PATH
cd /usr/local/addons/redmatic/var
npm install --save --no-package-lock --global-style --save-prefix="~" --production redmatic-webapp@0.2.1
/etc/config/rc.d/redmatic restart
```

**Comment by stan23** [comment]
Jupp, nach dem manuellen Update geht's :)
